---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: default
  labels:
    app: payments-service
spec:
  selector:
    app: payments-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP